[project]
name = "blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.117.1",
    "httpx>=0.28.1",
    "pydantic>=2.0,<3.0",
    "sqlalchemy>=2.0",
    "uvicorn>=0.36.0",
]

[dependency-groups]
dev = [
    "black>=25.9.0",
    "isort>=6.0.1",
    "mypy>=1.18.2",
    "pytest>=8.4.2",
]


# Tool configurations below
[tool.black]
line-length = 120

[tool.mypy]
strict = true
check_untyped_defs = true
disallow_untyped_decorators = false
exclude = ["\\.venv"]  # regex requires escaping backslashes for .
plugins = "sqlalchemy.ext.mypy.plugin"
ignore_missing_imports = true
mypy_path = ["."]

[tool.flake8]
max-line-length = 120
ignore = ["E203"]
exclude = [".venv", ".git"]

[tool.isort]
profile = "black"
filter_files = true


[tool.pytest.ini_options]
markers = [
    "integration: mark integration tests",
]
pythonpath = ["."]
testpaths = ["tests"]